// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<OneNoteSection> parseOneNote({required List<int> data}) =>
    RustLib.instance.api.crateApiSimpleParseOneNote(data: data);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OneNotePage>>
abstract class OneNotePage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OneNoteSection>>
abstract class OneNoteSection implements RustOpaqueInterface {
  String displayName();

  List<OneNotePage> pages();
}
