name: dart_pkgs
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/consoler
  - packages/consoler/example
  - packages/dart_leap
  - packages/flutter_localizer
  - packages/generate_leap
  - packages/keybinder
  - packages/keybinder/example
  - packages/localizer
  - packages/lw_file_system
  - packages/lw_file_system_api
  - packages/lw_sysapi
  - packages/lw_sysapi/example
  - packages/material_leap
  - packages/material_leap/example
  - packages/networker/networker
  - packages/networker/networker_crypto
  - packages/networker/networker_rtc
  - packages/networker/networker_s5
  - packages/networker/networker_socket
  - packages/onenote_parser
  - packages/onenote_parser/example
  - tools/app_tools

dependency_overrides:
  mime: ^2.0.0
