name: settings_leap
description: Flutter helpers for building searchable, expandable settings views.
version: 0.1.0
repository: https://github.com/LinwoodDev/dart_pkgs
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=1.17.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  material_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/material_leap
      ref: 8762753ddaa3843065cadce49c81f9b13a654a40
  phosphor_flutter:
    git:
      url: https://github.com/CodeDoctorDE/phosphor-flutter.git
      ref: 571650ac818f95a6c1f48f1bf3d33a010505d2c9

  material_ui: any
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
