name: settings_leap
description: Flutter helpers for building searchable, expandable settings views.
version: 0.1.0
repository: https://github.com/LinwoodDev/dart_pkgs
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=1.17.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  material_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/material_leap
      ref: 4eb8e369cc37adac6eac36a9ed1c352343c8aa32
  phosphor_flutter:
    git:
      url: https://github.com/CodeDoctorDE/phosphor-flutter.git
      ref: f7479596c67239e755ab1fe3bade84895bfd6222

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
