name: flutter_localizer
description: Simple to use flutter package to localize your app.
version: 1.0.1+1
homepage: https://github.com/LinwoodCloud/dart_pkgs
repository: https://github.com/LinwoodCloud/dart_pkgs
documentation: https://github.com/LinwoodCloud/dart_pkgs
issue_tracker: https://github.com/LinwoodCloud/dart_pkgs/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  flutter:
    sdk: flutter
  localizer: ^1.0.2
dev_dependencies:
  flutter_lints: ^6.0.0
