// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class OneNoteColor {
  final int alpha;
  final int red;
  final int green;
  final int blue;

  const OneNoteColor({
    required this.alpha,
    required this.red,
    required this.green,
    required this.blue,
  });

  @override
  int get hashCode =>
      alpha.hashCode ^ red.hashCode ^ green.hashCode ^ blue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteColor &&
          runtimeType == other.runtimeType &&
          alpha == other.alpha &&
          red == other.red &&
          green == other.green &&
          blue == other.blue;
}

@freezed
sealed class OneNoteContent with _$OneNoteContent {
  const OneNoteContent._();

  const factory OneNoteContent.richText(OneNoteRichText field0) =
      OneNoteContent_RichText;
  const factory OneNoteContent.table(OneNoteTable field0) =
      OneNoteContent_Table;
  const factory OneNoteContent.image(OneNoteImage field0) =
      OneNoteContent_Image;
  const factory OneNoteContent.embeddedFile(OneNoteEmbeddedFile field0) =
      OneNoteContent_EmbeddedFile;
  const factory OneNoteContent.ink(OneNoteInk field0) = OneNoteContent_Ink;
  const factory OneNoteContent.unknown() = OneNoteContent_Unknown;
}

class OneNoteEmbeddedFile {
  final String filename;
  final String fileType;
  final Uint8List data;
  final BigInt size;
  final double? layoutMaxWidth;
  final double? layoutMaxHeight;
  final double? offsetHorizontal;
  final double? offsetVertical;

  const OneNoteEmbeddedFile({
    required this.filename,
    required this.fileType,
    required this.data,
    required this.size,
    this.layoutMaxWidth,
    this.layoutMaxHeight,
    this.offsetHorizontal,
    this.offsetVertical,
  });

  @override
  int get hashCode =>
      filename.hashCode ^
      fileType.hashCode ^
      data.hashCode ^
      size.hashCode ^
      layoutMaxWidth.hashCode ^
      layoutMaxHeight.hashCode ^
      offsetHorizontal.hashCode ^
      offsetVertical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteEmbeddedFile &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          fileType == other.fileType &&
          data == other.data &&
          size == other.size &&
          layoutMaxWidth == other.layoutMaxWidth &&
          layoutMaxHeight == other.layoutMaxHeight &&
          offsetHorizontal == other.offsetHorizontal &&
          offsetVertical == other.offsetVertical;
}

class OneNoteEmbeddedInk {
  final OneNoteInk ink;
  final OneNoteInkBoundingBox? displayBoundingBox;

  const OneNoteEmbeddedInk({required this.ink, this.displayBoundingBox});

  @override
  int get hashCode => ink.hashCode ^ displayBoundingBox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteEmbeddedInk &&
          runtimeType == other.runtimeType &&
          ink == other.ink &&
          displayBoundingBox == other.displayBoundingBox;
}

class OneNoteEmbeddedInkSpace {
  final double width;
  final double height;

  const OneNoteEmbeddedInkSpace({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteEmbeddedInkSpace &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

@freezed
sealed class OneNoteEmbeddedObject with _$OneNoteEmbeddedObject {
  const OneNoteEmbeddedObject._();

  const factory OneNoteEmbeddedObject.ink(OneNoteEmbeddedInk field0) =
      OneNoteEmbeddedObject_Ink;
  const factory OneNoteEmbeddedObject.inkSpace(OneNoteEmbeddedInkSpace field0) =
      OneNoteEmbeddedObject_InkSpace;
  const factory OneNoteEmbeddedObject.inkLineBreak() =
      OneNoteEmbeddedObject_InkLineBreak;
}

class OneNoteImage {
  final Uint8List? data;
  final BigInt? size;
  final String? extension_;
  final String? filename;
  final String? altText;
  final String? ocrText;
  final int? textLanguageCode;
  final String? hyperlinkUrl;
  final int? displayedPageNumber;
  final double? pictureWidth;
  final double? pictureHeight;
  final double? layoutMaxWidth;
  final double? layoutMaxHeight;
  final double? offsetHorizontal;
  final double? offsetVertical;
  final bool isBackground;

  const OneNoteImage({
    this.data,
    this.size,
    this.extension_,
    this.filename,
    this.altText,
    this.ocrText,
    this.textLanguageCode,
    this.hyperlinkUrl,
    this.displayedPageNumber,
    this.pictureWidth,
    this.pictureHeight,
    this.layoutMaxWidth,
    this.layoutMaxHeight,
    this.offsetHorizontal,
    this.offsetVertical,
    required this.isBackground,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      size.hashCode ^
      extension_.hashCode ^
      filename.hashCode ^
      altText.hashCode ^
      ocrText.hashCode ^
      textLanguageCode.hashCode ^
      hyperlinkUrl.hashCode ^
      displayedPageNumber.hashCode ^
      pictureWidth.hashCode ^
      pictureHeight.hashCode ^
      layoutMaxWidth.hashCode ^
      layoutMaxHeight.hashCode ^
      offsetHorizontal.hashCode ^
      offsetVertical.hashCode ^
      isBackground.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteImage &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          size == other.size &&
          extension_ == other.extension_ &&
          filename == other.filename &&
          altText == other.altText &&
          ocrText == other.ocrText &&
          textLanguageCode == other.textLanguageCode &&
          hyperlinkUrl == other.hyperlinkUrl &&
          displayedPageNumber == other.displayedPageNumber &&
          pictureWidth == other.pictureWidth &&
          pictureHeight == other.pictureHeight &&
          layoutMaxWidth == other.layoutMaxWidth &&
          layoutMaxHeight == other.layoutMaxHeight &&
          offsetHorizontal == other.offsetHorizontal &&
          offsetVertical == other.offsetVertical &&
          isBackground == other.isBackground;
}

class OneNoteInk {
  final List<OneNoteInkStroke> strokes;
  final List<OneNoteInk> childGroups;
  final OneNoteInkBoundingBox? boundingBox;
  final double? offsetHorizontal;
  final double? offsetVertical;

  const OneNoteInk({
    required this.strokes,
    required this.childGroups,
    this.boundingBox,
    this.offsetHorizontal,
    this.offsetVertical,
  });

  @override
  int get hashCode =>
      strokes.hashCode ^
      childGroups.hashCode ^
      boundingBox.hashCode ^
      offsetHorizontal.hashCode ^
      offsetVertical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteInk &&
          runtimeType == other.runtimeType &&
          strokes == other.strokes &&
          childGroups == other.childGroups &&
          boundingBox == other.boundingBox &&
          offsetHorizontal == other.offsetHorizontal &&
          offsetVertical == other.offsetVertical;
}

class OneNoteInkBoundingBox {
  final double x;
  final double y;
  final double height;
  final double width;

  const OneNoteInkBoundingBox({
    required this.x,
    required this.y,
    required this.height,
    required this.width,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ height.hashCode ^ width.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteInkBoundingBox &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          height == other.height &&
          width == other.width;
}

class OneNoteInkPoint {
  final double x;
  final double y;

  const OneNoteInkPoint({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteInkPoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class OneNoteInkStroke {
  final List<OneNoteInkPoint> path;
  final int? penTip;
  final int? transparency;
  final double height;
  final double width;
  final int? color;
  final String? recognizedText;

  const OneNoteInkStroke({
    required this.path,
    this.penTip,
    this.transparency,
    required this.height,
    required this.width,
    this.color,
    this.recognizedText,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      penTip.hashCode ^
      transparency.hashCode ^
      height.hashCode ^
      width.hashCode ^
      color.hashCode ^
      recognizedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteInkStroke &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          penTip == other.penTip &&
          transparency == other.transparency &&
          height == other.height &&
          width == other.width &&
          color == other.color &&
          recognizedText == other.recognizedText;
}

class OneNoteNotebook {
  final List<OneNoteSectionEntry> entries;
  final OneNoteColor? color;
  final List<OneNoteWarning> warnings;

  const OneNoteNotebook({
    required this.entries,
    this.color,
    required this.warnings,
  });

  @override
  int get hashCode => entries.hashCode ^ color.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteNotebook &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          color == other.color &&
          warnings == other.warnings;
}

class OneNoteOutline {
  final int childLevel;
  final double? listSpacing;
  final Float32List indents;
  final String? alignmentInParent;
  final String? alignmentSelf;
  final double? layoutMaxHeight;
  final double? layoutMaxWidth;
  final double? layoutReservedWidth;
  final double? layoutMinimumWidth;
  final bool isLayoutSizeSetByUser;
  final double? offsetHorizontal;
  final double? offsetVertical;
  final List<OneNoteOutlineItem> items;

  const OneNoteOutline({
    required this.childLevel,
    this.listSpacing,
    required this.indents,
    this.alignmentInParent,
    this.alignmentSelf,
    this.layoutMaxHeight,
    this.layoutMaxWidth,
    this.layoutReservedWidth,
    this.layoutMinimumWidth,
    required this.isLayoutSizeSetByUser,
    this.offsetHorizontal,
    this.offsetVertical,
    required this.items,
  });

  @override
  int get hashCode =>
      childLevel.hashCode ^
      listSpacing.hashCode ^
      indents.hashCode ^
      alignmentInParent.hashCode ^
      alignmentSelf.hashCode ^
      layoutMaxHeight.hashCode ^
      layoutMaxWidth.hashCode ^
      layoutReservedWidth.hashCode ^
      layoutMinimumWidth.hashCode ^
      isLayoutSizeSetByUser.hashCode ^
      offsetHorizontal.hashCode ^
      offsetVertical.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteOutline &&
          runtimeType == other.runtimeType &&
          childLevel == other.childLevel &&
          listSpacing == other.listSpacing &&
          indents == other.indents &&
          alignmentInParent == other.alignmentInParent &&
          alignmentSelf == other.alignmentSelf &&
          layoutMaxHeight == other.layoutMaxHeight &&
          layoutMaxWidth == other.layoutMaxWidth &&
          layoutReservedWidth == other.layoutReservedWidth &&
          layoutMinimumWidth == other.layoutMinimumWidth &&
          isLayoutSizeSetByUser == other.isLayoutSizeSetByUser &&
          offsetHorizontal == other.offsetHorizontal &&
          offsetVertical == other.offsetVertical &&
          items == other.items;
}

class OneNoteOutlineElement {
  final List<OneNoteContent> contents;
  final double? listSpacing;
  final int childLevel;
  final List<OneNoteOutlineItem> children;

  const OneNoteOutlineElement({
    required this.contents,
    this.listSpacing,
    required this.childLevel,
    required this.children,
  });

  @override
  int get hashCode =>
      contents.hashCode ^
      listSpacing.hashCode ^
      childLevel.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteOutlineElement &&
          runtimeType == other.runtimeType &&
          contents == other.contents &&
          listSpacing == other.listSpacing &&
          childLevel == other.childLevel &&
          children == other.children;
}

class OneNoteOutlineGroup {
  final int childLevel;
  final List<OneNoteOutlineItem> items;

  const OneNoteOutlineGroup({required this.childLevel, required this.items});

  @override
  int get hashCode => childLevel.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteOutlineGroup &&
          runtimeType == other.runtimeType &&
          childLevel == other.childLevel &&
          items == other.items;
}

@freezed
sealed class OneNoteOutlineItem with _$OneNoteOutlineItem {
  const OneNoteOutlineItem._();

  const factory OneNoteOutlineItem.group(OneNoteOutlineGroup field0) =
      OneNoteOutlineItem_Group;
  const factory OneNoteOutlineItem.element(OneNoteOutlineElement field0) =
      OneNoteOutlineItem_Element;
}

class OneNotePage {
  final String linkTargetId;
  final String? title;
  final int level;
  final String createdAt;
  final String updatedAt;
  final String? author;
  final double? height;
  final List<OneNotePageContent> contents;
  final String? recognizedText;

  const OneNotePage({
    required this.linkTargetId,
    this.title,
    required this.level,
    required this.createdAt,
    required this.updatedAt,
    this.author,
    this.height,
    required this.contents,
    this.recognizedText,
  });

  @override
  int get hashCode =>
      linkTargetId.hashCode ^
      title.hashCode ^
      level.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      author.hashCode ^
      height.hashCode ^
      contents.hashCode ^
      recognizedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNotePage &&
          runtimeType == other.runtimeType &&
          linkTargetId == other.linkTargetId &&
          title == other.title &&
          level == other.level &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          author == other.author &&
          height == other.height &&
          contents == other.contents &&
          recognizedText == other.recognizedText;
}

@freezed
sealed class OneNotePageContent with _$OneNotePageContent {
  const OneNotePageContent._();

  const factory OneNotePageContent.outline(OneNoteOutline field0) =
      OneNotePageContent_Outline;
  const factory OneNotePageContent.image(OneNoteImage field0) =
      OneNotePageContent_Image;
  const factory OneNotePageContent.embeddedFile(OneNoteEmbeddedFile field0) =
      OneNotePageContent_EmbeddedFile;
  const factory OneNotePageContent.ink(OneNoteInk field0) =
      OneNotePageContent_Ink;
  const factory OneNotePageContent.unknown() = OneNotePageContent_Unknown;
}

class OneNotePageSeries {
  final List<OneNotePage> pages;

  const OneNotePageSeries({required this.pages});

  @override
  int get hashCode => pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNotePageSeries &&
          runtimeType == other.runtimeType &&
          pages == other.pages;
}

class OneNoteRichText {
  final String text;
  final Uint32List textRunIndices;
  final List<OneNoteTextStyle> textRunStyles;
  final OneNoteTextStyle paragraphStyle;
  final double paragraphSpaceBefore;
  final double paragraphSpaceAfter;
  final double? paragraphLineSpacingExact;
  final String paragraphAlignment;
  final List<OneNoteEmbeddedObject> embeddedObjects;

  const OneNoteRichText({
    required this.text,
    required this.textRunIndices,
    required this.textRunStyles,
    required this.paragraphStyle,
    required this.paragraphSpaceBefore,
    required this.paragraphSpaceAfter,
    this.paragraphLineSpacingExact,
    required this.paragraphAlignment,
    required this.embeddedObjects,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      textRunIndices.hashCode ^
      textRunStyles.hashCode ^
      paragraphStyle.hashCode ^
      paragraphSpaceBefore.hashCode ^
      paragraphSpaceAfter.hashCode ^
      paragraphLineSpacingExact.hashCode ^
      paragraphAlignment.hashCode ^
      embeddedObjects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteRichText &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          textRunIndices == other.textRunIndices &&
          textRunStyles == other.textRunStyles &&
          paragraphStyle == other.paragraphStyle &&
          paragraphSpaceBefore == other.paragraphSpaceBefore &&
          paragraphSpaceAfter == other.paragraphSpaceAfter &&
          paragraphLineSpacingExact == other.paragraphLineSpacingExact &&
          paragraphAlignment == other.paragraphAlignment &&
          embeddedObjects == other.embeddedObjects;
}

class OneNoteSection {
  final String displayName;
  final List<OneNotePageSeries> pageSeries;
  final OneNoteColor? color;
  final List<OneNoteWarning> warnings;

  const OneNoteSection({
    required this.displayName,
    required this.pageSeries,
    this.color,
    required this.warnings,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      pageSeries.hashCode ^
      color.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteSection &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          pageSeries == other.pageSeries &&
          color == other.color &&
          warnings == other.warnings;
}

@freezed
sealed class OneNoteSectionEntry with _$OneNoteSectionEntry {
  const OneNoteSectionEntry._();

  const factory OneNoteSectionEntry.section(OneNoteSection field0) =
      OneNoteSectionEntry_Section;
  const factory OneNoteSectionEntry.sectionGroup(OneNoteSectionGroup field0) =
      OneNoteSectionEntry_SectionGroup;
}

class OneNoteSectionGroup {
  final String displayName;
  final List<OneNoteSectionEntry> entries;

  const OneNoteSectionGroup({required this.displayName, required this.entries});

  @override
  int get hashCode => displayName.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteSectionGroup &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          entries == other.entries;
}

class OneNoteTable {
  final int rowCount;
  final int columnCount;
  final List<OneNoteTableRow> rows;
  final Uint8List lockedColumns;
  final Float32List columnWidths;
  final bool bordersVisible;

  const OneNoteTable({
    required this.rowCount,
    required this.columnCount,
    required this.rows,
    required this.lockedColumns,
    required this.columnWidths,
    required this.bordersVisible,
  });

  @override
  int get hashCode =>
      rowCount.hashCode ^
      columnCount.hashCode ^
      rows.hashCode ^
      lockedColumns.hashCode ^
      columnWidths.hashCode ^
      bordersVisible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteTable &&
          runtimeType == other.runtimeType &&
          rowCount == other.rowCount &&
          columnCount == other.columnCount &&
          rows == other.rows &&
          lockedColumns == other.lockedColumns &&
          columnWidths == other.columnWidths &&
          bordersVisible == other.bordersVisible;
}

class OneNoteTableCell {
  final List<OneNoteOutlineElement> contents;
  final OneNoteColor? backgroundColor;
  final double? layoutMaxWidth;
  final Float32List indents;

  const OneNoteTableCell({
    required this.contents,
    this.backgroundColor,
    this.layoutMaxWidth,
    required this.indents,
  });

  @override
  int get hashCode =>
      contents.hashCode ^
      backgroundColor.hashCode ^
      layoutMaxWidth.hashCode ^
      indents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteTableCell &&
          runtimeType == other.runtimeType &&
          contents == other.contents &&
          backgroundColor == other.backgroundColor &&
          layoutMaxWidth == other.layoutMaxWidth &&
          indents == other.indents;
}

class OneNoteTableRow {
  final List<OneNoteTableCell> cells;

  const OneNoteTableRow({required this.cells});

  @override
  int get hashCode => cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteTableRow &&
          runtimeType == other.runtimeType &&
          cells == other.cells;
}

class OneNoteTextStyle {
  final bool bold;
  final bool italic;
  final bool underline;
  final bool strikethrough;
  final bool superscript;
  final bool subscript;
  final String? font;
  final int? fontSize;
  final String? nextStyle;
  final String? styleId;
  final String? paragraphAlignment;
  final int? languageCode;
  final bool mathFormatting;
  final bool hyperlink;
  final bool hyperlinkProtected;
  final bool hidden;

  const OneNoteTextStyle({
    required this.bold,
    required this.italic,
    required this.underline,
    required this.strikethrough,
    required this.superscript,
    required this.subscript,
    this.font,
    this.fontSize,
    this.nextStyle,
    this.styleId,
    this.paragraphAlignment,
    this.languageCode,
    required this.mathFormatting,
    required this.hyperlink,
    required this.hyperlinkProtected,
    required this.hidden,
  });

  @override
  int get hashCode =>
      bold.hashCode ^
      italic.hashCode ^
      underline.hashCode ^
      strikethrough.hashCode ^
      superscript.hashCode ^
      subscript.hashCode ^
      font.hashCode ^
      fontSize.hashCode ^
      nextStyle.hashCode ^
      styleId.hashCode ^
      paragraphAlignment.hashCode ^
      languageCode.hashCode ^
      mathFormatting.hashCode ^
      hyperlink.hashCode ^
      hyperlinkProtected.hashCode ^
      hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteTextStyle &&
          runtimeType == other.runtimeType &&
          bold == other.bold &&
          italic == other.italic &&
          underline == other.underline &&
          strikethrough == other.strikethrough &&
          superscript == other.superscript &&
          subscript == other.subscript &&
          font == other.font &&
          fontSize == other.fontSize &&
          nextStyle == other.nextStyle &&
          styleId == other.styleId &&
          paragraphAlignment == other.paragraphAlignment &&
          languageCode == other.languageCode &&
          mathFormatting == other.mathFormatting &&
          hyperlink == other.hyperlink &&
          hyperlinkProtected == other.hyperlinkProtected &&
          hidden == other.hidden;
}

class OneNoteWarning {
  final String message;
  final String? pageId;
  final String? pageTitle;

  const OneNoteWarning({required this.message, this.pageId, this.pageTitle});

  @override
  int get hashCode => message.hashCode ^ pageId.hashCode ^ pageTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneNoteWarning &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          pageId == other.pageId &&
          pageTitle == other.pageTitle;
}
