// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `color`, `content`, `debug`, `embedded_file`, `image`, `ink_bounding_box`, `ink_point`, `ink_stroke`, `ink`, `notebook`, `outline_element`, `outline_group`, `outline_item`, `outline`, `page_content`, `page_series`, `page`, `read_all`, `rich_text`, `section_entry`, `section_group`, `section`, `table_cell`, `table_row`, `table`, `text_style`, `warnings`

/// Parse a `.onetoc2` notebook file.
Future<OneNoteNotebook> parseNotebook({required String path}) =>
    RustLib.instance.api.crateApiOnenoteParseNotebook(path: path);

/// Parse a `.one` section file.
Future<OneNoteSection> parseSection({required String path}) =>
    RustLib.instance.api.crateApiOnenoteParseSection(path: path);

/// Parse a `.onepkg` notebook archive.
Future<OneNoteNotebook> parsePackage({required String path}) =>
    RustLib.instance.api.crateApiOnenoteParsePackage(path: path);

/// Parse a `.one` section from bytes. This works on native platforms and web.
Future<OneNoteSection> parseSectionBytes({
  required List<int> data,
  required String fileName,
}) => RustLib.instance.api.crateApiOnenoteParseSectionBytes(
  data: data,
  fileName: fileName,
);

/// Parse a `.onepkg` archive from bytes. This works on native platforms and web.
Future<OneNoteNotebook> parsePackageBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiOnenoteParsePackageBytes(data: data);

/// Dump the low-level OneStore representation for diagnostic tools.
Future<String> dumpOnestore({required List<int> data}) =>
    RustLib.instance.api.crateApiOnenoteDumpOnestore(data: data);
