// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/model.dart';
import 'api/onenote.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  OneNoteColor dco_decode_box_autoadd_one_note_color(dynamic raw);

  @protected
  OneNoteEmbeddedFile dco_decode_box_autoadd_one_note_embedded_file(
    dynamic raw,
  );

  @protected
  OneNoteEmbeddedInk dco_decode_box_autoadd_one_note_embedded_ink(dynamic raw);

  @protected
  OneNoteEmbeddedInkSpace dco_decode_box_autoadd_one_note_embedded_ink_space(
    dynamic raw,
  );

  @protected
  OneNoteImage dco_decode_box_autoadd_one_note_image(dynamic raw);

  @protected
  OneNoteInk dco_decode_box_autoadd_one_note_ink(dynamic raw);

  @protected
  OneNoteInkBoundingBox dco_decode_box_autoadd_one_note_ink_bounding_box(
    dynamic raw,
  );

  @protected
  OneNoteOutline dco_decode_box_autoadd_one_note_outline(dynamic raw);

  @protected
  OneNoteOutlineElement dco_decode_box_autoadd_one_note_outline_element(
    dynamic raw,
  );

  @protected
  OneNoteOutlineGroup dco_decode_box_autoadd_one_note_outline_group(
    dynamic raw,
  );

  @protected
  OneNoteRichText dco_decode_box_autoadd_one_note_rich_text(dynamic raw);

  @protected
  OneNoteSection dco_decode_box_autoadd_one_note_section(dynamic raw);

  @protected
  OneNoteSectionGroup dco_decode_box_autoadd_one_note_section_group(
    dynamic raw,
  );

  @protected
  OneNoteTable dco_decode_box_autoadd_one_note_table(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<OneNoteContent> dco_decode_list_one_note_content(dynamic raw);

  @protected
  List<OneNoteEmbeddedObject> dco_decode_list_one_note_embedded_object(
    dynamic raw,
  );

  @protected
  List<OneNoteInk> dco_decode_list_one_note_ink(dynamic raw);

  @protected
  List<OneNoteInkPoint> dco_decode_list_one_note_ink_point(dynamic raw);

  @protected
  List<OneNoteInkStroke> dco_decode_list_one_note_ink_stroke(dynamic raw);

  @protected
  List<OneNoteOutlineElement> dco_decode_list_one_note_outline_element(
    dynamic raw,
  );

  @protected
  List<OneNoteOutlineItem> dco_decode_list_one_note_outline_item(dynamic raw);

  @protected
  List<OneNotePage> dco_decode_list_one_note_page(dynamic raw);

  @protected
  List<OneNotePageContent> dco_decode_list_one_note_page_content(dynamic raw);

  @protected
  List<OneNotePageSeries> dco_decode_list_one_note_page_series(dynamic raw);

  @protected
  List<OneNoteSectionEntry> dco_decode_list_one_note_section_entry(dynamic raw);

  @protected
  List<OneNoteTableCell> dco_decode_list_one_note_table_cell(dynamic raw);

  @protected
  List<OneNoteTableRow> dco_decode_list_one_note_table_row(dynamic raw);

  @protected
  List<OneNoteTextStyle> dco_decode_list_one_note_text_style(dynamic raw);

  @protected
  List<OneNoteWarning> dco_decode_list_one_note_warning(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OneNoteColor dco_decode_one_note_color(dynamic raw);

  @protected
  OneNoteContent dco_decode_one_note_content(dynamic raw);

  @protected
  OneNoteEmbeddedFile dco_decode_one_note_embedded_file(dynamic raw);

  @protected
  OneNoteEmbeddedInk dco_decode_one_note_embedded_ink(dynamic raw);

  @protected
  OneNoteEmbeddedInkSpace dco_decode_one_note_embedded_ink_space(dynamic raw);

  @protected
  OneNoteEmbeddedObject dco_decode_one_note_embedded_object(dynamic raw);

  @protected
  OneNoteImage dco_decode_one_note_image(dynamic raw);

  @protected
  OneNoteInk dco_decode_one_note_ink(dynamic raw);

  @protected
  OneNoteInkBoundingBox dco_decode_one_note_ink_bounding_box(dynamic raw);

  @protected
  OneNoteInkPoint dco_decode_one_note_ink_point(dynamic raw);

  @protected
  OneNoteInkStroke dco_decode_one_note_ink_stroke(dynamic raw);

  @protected
  OneNoteNotebook dco_decode_one_note_notebook(dynamic raw);

  @protected
  OneNoteOutline dco_decode_one_note_outline(dynamic raw);

  @protected
  OneNoteOutlineElement dco_decode_one_note_outline_element(dynamic raw);

  @protected
  OneNoteOutlineGroup dco_decode_one_note_outline_group(dynamic raw);

  @protected
  OneNoteOutlineItem dco_decode_one_note_outline_item(dynamic raw);

  @protected
  OneNotePage dco_decode_one_note_page(dynamic raw);

  @protected
  OneNotePageContent dco_decode_one_note_page_content(dynamic raw);

  @protected
  OneNotePageSeries dco_decode_one_note_page_series(dynamic raw);

  @protected
  OneNoteRichText dco_decode_one_note_rich_text(dynamic raw);

  @protected
  OneNoteSection dco_decode_one_note_section(dynamic raw);

  @protected
  OneNoteSectionEntry dco_decode_one_note_section_entry(dynamic raw);

  @protected
  OneNoteSectionGroup dco_decode_one_note_section_group(dynamic raw);

  @protected
  OneNoteTable dco_decode_one_note_table(dynamic raw);

  @protected
  OneNoteTableCell dco_decode_one_note_table_cell(dynamic raw);

  @protected
  OneNoteTableRow dco_decode_one_note_table_row(dynamic raw);

  @protected
  OneNoteTextStyle dco_decode_one_note_text_style(dynamic raw);

  @protected
  OneNoteWarning dco_decode_one_note_warning(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  OneNoteColor? dco_decode_opt_box_autoadd_one_note_color(dynamic raw);

  @protected
  OneNoteInkBoundingBox? dco_decode_opt_box_autoadd_one_note_ink_bounding_box(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  OneNoteColor sse_decode_box_autoadd_one_note_color(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteEmbeddedFile sse_decode_box_autoadd_one_note_embedded_file(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteEmbeddedInk sse_decode_box_autoadd_one_note_embedded_ink(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteEmbeddedInkSpace sse_decode_box_autoadd_one_note_embedded_ink_space(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteImage sse_decode_box_autoadd_one_note_image(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteInk sse_decode_box_autoadd_one_note_ink(SseDeserializer deserializer);

  @protected
  OneNoteInkBoundingBox sse_decode_box_autoadd_one_note_ink_bounding_box(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteOutline sse_decode_box_autoadd_one_note_outline(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteOutlineElement sse_decode_box_autoadd_one_note_outline_element(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteOutlineGroup sse_decode_box_autoadd_one_note_outline_group(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteRichText sse_decode_box_autoadd_one_note_rich_text(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteSection sse_decode_box_autoadd_one_note_section(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteSectionGroup sse_decode_box_autoadd_one_note_section_group(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteTable sse_decode_box_autoadd_one_note_table(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<OneNoteContent> sse_decode_list_one_note_content(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteEmbeddedObject> sse_decode_list_one_note_embedded_object(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteInk> sse_decode_list_one_note_ink(SseDeserializer deserializer);

  @protected
  List<OneNoteInkPoint> sse_decode_list_one_note_ink_point(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteInkStroke> sse_decode_list_one_note_ink_stroke(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteOutlineElement> sse_decode_list_one_note_outline_element(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteOutlineItem> sse_decode_list_one_note_outline_item(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNotePage> sse_decode_list_one_note_page(SseDeserializer deserializer);

  @protected
  List<OneNotePageContent> sse_decode_list_one_note_page_content(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNotePageSeries> sse_decode_list_one_note_page_series(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteSectionEntry> sse_decode_list_one_note_section_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteTableCell> sse_decode_list_one_note_table_cell(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteTableRow> sse_decode_list_one_note_table_row(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteTextStyle> sse_decode_list_one_note_text_style(
    SseDeserializer deserializer,
  );

  @protected
  List<OneNoteWarning> sse_decode_list_one_note_warning(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OneNoteColor sse_decode_one_note_color(SseDeserializer deserializer);

  @protected
  OneNoteContent sse_decode_one_note_content(SseDeserializer deserializer);

  @protected
  OneNoteEmbeddedFile sse_decode_one_note_embedded_file(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteEmbeddedInk sse_decode_one_note_embedded_ink(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteEmbeddedInkSpace sse_decode_one_note_embedded_ink_space(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteEmbeddedObject sse_decode_one_note_embedded_object(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteImage sse_decode_one_note_image(SseDeserializer deserializer);

  @protected
  OneNoteInk sse_decode_one_note_ink(SseDeserializer deserializer);

  @protected
  OneNoteInkBoundingBox sse_decode_one_note_ink_bounding_box(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteInkPoint sse_decode_one_note_ink_point(SseDeserializer deserializer);

  @protected
  OneNoteInkStroke sse_decode_one_note_ink_stroke(SseDeserializer deserializer);

  @protected
  OneNoteNotebook sse_decode_one_note_notebook(SseDeserializer deserializer);

  @protected
  OneNoteOutline sse_decode_one_note_outline(SseDeserializer deserializer);

  @protected
  OneNoteOutlineElement sse_decode_one_note_outline_element(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteOutlineGroup sse_decode_one_note_outline_group(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteOutlineItem sse_decode_one_note_outline_item(
    SseDeserializer deserializer,
  );

  @protected
  OneNotePage sse_decode_one_note_page(SseDeserializer deserializer);

  @protected
  OneNotePageContent sse_decode_one_note_page_content(
    SseDeserializer deserializer,
  );

  @protected
  OneNotePageSeries sse_decode_one_note_page_series(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteRichText sse_decode_one_note_rich_text(SseDeserializer deserializer);

  @protected
  OneNoteSection sse_decode_one_note_section(SseDeserializer deserializer);

  @protected
  OneNoteSectionEntry sse_decode_one_note_section_entry(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteSectionGroup sse_decode_one_note_section_group(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteTable sse_decode_one_note_table(SseDeserializer deserializer);

  @protected
  OneNoteTableCell sse_decode_one_note_table_cell(SseDeserializer deserializer);

  @protected
  OneNoteTableRow sse_decode_one_note_table_row(SseDeserializer deserializer);

  @protected
  OneNoteTextStyle sse_decode_one_note_text_style(SseDeserializer deserializer);

  @protected
  OneNoteWarning sse_decode_one_note_warning(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  OneNoteColor? sse_decode_opt_box_autoadd_one_note_color(
    SseDeserializer deserializer,
  );

  @protected
  OneNoteInkBoundingBox? sse_decode_opt_box_autoadd_one_note_ink_bounding_box(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_one_note_color(
    OneNoteColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_embedded_file(
    OneNoteEmbeddedFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_embedded_ink(
    OneNoteEmbeddedInk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_embedded_ink_space(
    OneNoteEmbeddedInkSpace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_image(
    OneNoteImage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_ink(
    OneNoteInk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_ink_bounding_box(
    OneNoteInkBoundingBox self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_outline(
    OneNoteOutline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_outline_element(
    OneNoteOutlineElement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_outline_group(
    OneNoteOutlineGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_rich_text(
    OneNoteRichText self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_section(
    OneNoteSection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_section_group(
    OneNoteSectionGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_one_note_table(
    OneNoteTable self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_one_note_content(
    List<OneNoteContent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_embedded_object(
    List<OneNoteEmbeddedObject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_ink(
    List<OneNoteInk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_ink_point(
    List<OneNoteInkPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_ink_stroke(
    List<OneNoteInkStroke> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_outline_element(
    List<OneNoteOutlineElement> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_outline_item(
    List<OneNoteOutlineItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_page(
    List<OneNotePage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_page_content(
    List<OneNotePageContent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_page_series(
    List<OneNotePageSeries> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_section_entry(
    List<OneNoteSectionEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_table_cell(
    List<OneNoteTableCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_table_row(
    List<OneNoteTableRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_text_style(
    List<OneNoteTextStyle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_one_note_warning(
    List<OneNoteWarning> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_color(OneNoteColor self, SseSerializer serializer);

  @protected
  void sse_encode_one_note_content(
    OneNoteContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_embedded_file(
    OneNoteEmbeddedFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_embedded_ink(
    OneNoteEmbeddedInk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_embedded_ink_space(
    OneNoteEmbeddedInkSpace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_embedded_object(
    OneNoteEmbeddedObject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_image(OneNoteImage self, SseSerializer serializer);

  @protected
  void sse_encode_one_note_ink(OneNoteInk self, SseSerializer serializer);

  @protected
  void sse_encode_one_note_ink_bounding_box(
    OneNoteInkBoundingBox self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_ink_point(
    OneNoteInkPoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_ink_stroke(
    OneNoteInkStroke self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_notebook(
    OneNoteNotebook self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_outline(
    OneNoteOutline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_outline_element(
    OneNoteOutlineElement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_outline_group(
    OneNoteOutlineGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_outline_item(
    OneNoteOutlineItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_page(OneNotePage self, SseSerializer serializer);

  @protected
  void sse_encode_one_note_page_content(
    OneNotePageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_page_series(
    OneNotePageSeries self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_rich_text(
    OneNoteRichText self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_section(
    OneNoteSection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_section_entry(
    OneNoteSectionEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_section_group(
    OneNoteSectionGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_table(OneNoteTable self, SseSerializer serializer);

  @protected
  void sse_encode_one_note_table_cell(
    OneNoteTableCell self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_table_row(
    OneNoteTableRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_text_style(
    OneNoteTextStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_one_note_warning(
    OneNoteWarning self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_one_note_color(
    OneNoteColor? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_one_note_ink_bounding_box(
    OneNoteInkBoundingBox? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
