arb-dir: lib/l10n
template-arb-file: keybinder_en.arb
output-localization-file: keybinder_localizations.dart
output-class: KeybinderLocalizations
synthetic-package: false
nullable-getter: false
format: true
