name: settings_leap_example
description: Example application for settings_leap.
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  settings_leap:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
